services:
  db:
    image: postgres:16
    container_name: fantasy_ranker_db
    environment:
      POSTGRES_DB: fantasy_ranker
      POSTGRES_USER: fantasy
      POSTGRES_PASSWORD: fantasy
    ports:
      - "5433:5432"
